// <auto-generated />
namespace Rafael.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AtuaiarBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtuaiarBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181301140_AtuaiarBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
